POST https://api.cloudflare.com/client/v4/zones/{{$dotenv ZONE_ID}}/workers/routes HTTP/1.1
X-Auth-Email: {{$dotenv EMAIL}}
X-Auth-Key: {{$dotenv API_KEY}}
Content-Type: application/json

{
  "pattern": "yujohnnattrass.dev/*",
  "script": "ab-test"
}