
PUT https://api.cloudflare.com/client/v4/accounts/WORKER_ACCOUNT_ID/storage/kv/namespaces/NAMESPACE_ID/values/ab-config HTTP/1.1
X-Auth-Email: EMAIL
X-Auth-Key: API_KEY
Content-Type: application/json

{
  "split": 50,
  "controlUrl": "ENTER CONTROL URL",
  "controlGA": "ENTER Google Analytic SCRIPT AND REMOVE NEWLINE CHARACTERS",
  "testUrl": "ENTER TEST URL",
  "testGA": "ENTER Google Analytic SCRIPT AND REMOVE NEWLINE CHARACTERS"
}
